apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app4-project
spec:
  description: "Project for app4"
  sourceRepos:
  - '*'
  destinations:
  - namespace: app4-namespace
    server: 'https://kubernetes.default.svc'
