apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - route.yaml
patches:
  - path: patch_deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: app1-deployment
  #- path: patch_route_host.yaml 
    #target:
      #group: route.openshift.io
      #version: v1
      #kind: Route
      #name: app1-route

