apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment-pruebas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
      environment: pruebas
  template:
    metadata:
      labels:
        app: app1
        environment: pruebas
    spec:
      containers:
      - name: app1-container
        image: bhargavshah86/kube-test:v0.1
        ports:
        - containerPort: 80
