apiVersion: v1
kind: Service
metadata:
  name: app1-service-pruebas
spec:
  selector:
    app: app1
    environment: pruebas
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
