apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
spec:
  project: default
  source:
    repoURL: 'https://github.com/amarti43/miargocd'
    targetRevision: HEAD
    path: areas/area1/app2/overlays/desarrollo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app2-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
