apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app5-project
spec:
  description: "Project for app5"
  sourceRepos:
  - '*'
  destinations:
  - namespace: app5-namespace
    server: 'https://kubernetes.default.svc'
