apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-pruebas
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: app1-container
        image: mi-repositorio/app1:desarrollo
