apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/amarti43/miargocd'
    targetRevision: HEAD
    path: 'deploy/argocd'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demo1
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

