apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: app1-container
        image: quay.io/redhattraining/hello-world-nginx:latest
